version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    volumes:
      - russian_vocabulary_flash_cards_dev_db:/var/lib/postgresql/data

  cache:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      REDIS_MASTER_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env.dev
    ports:
      - 6379:6379

volumes:
  russian_vocabulary_flash_cards_dev_db: