version: "3.1"

services:
  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main-test
    ports:
      - 5432:5432

  cache:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      REDIS_PASSWORD: mBdbh^jfhAOC0d
    ports:
      - 6379:6379