version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - russian_vocabulary_flash_cards_dev_db:/var/lib/postgresql/data

  cache:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      REDIS_PASSWORD: PPmfrw_lXjge1r
    ports:
      - 6379:6379

volumes:
  russian_vocabulary_flash_cards_dev_db: