version: "3.1"

services:
  db-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main-test
    restart: always
    ports:
      - 5433:5432