export const GenericValidationErrorCodes = {
  IS_EMPTY: 'IS_EMPTY',
  IS_LESS_THAN_MIN_LENGTH: 'IS_LESS_THAN_MIN_LENGTH',
  IS_MORE_THAN_MAX_LENGTH: 'IS_MORE_THAN_MAX_LENGTH',
  IS_NOT_BOOLEAN: 'IS_NOT_BOOLEAN',
  IS_NOT_BOOLEAN_STRING: 'IS_NOT_BOOLEAN_STRING',
  IS_NOT_STRING: 'IS_NOT_STRING',
  IS_NOT_NUMERIC_STRING: 'IS_NOT_NUMERIC_STRING',
  IS_NOT_NUMBER: 'IS_NOT_NUMBER',
  IS_NOT_VALID_ENUM_VALUE: 'IS_NOT_VALID_ENUM_VALUE',
  ONE_OF_THE_DEPENDENCIES_IS_MISSING: 'ONE_OF_THE_DEPENDENCIES_IS_MISSING',
};

export const UserValidationErrorCodes = {
  IS_NOT_VALID_EMAIL: 'IS_NOT_VALID_EMAIL',
};
