name: Test

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Environment
        run: echo 'RUNNING ENV'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Migrations
        run: echo 'MIGRATION RUN'
      - name: Seeding Database
        run: echo 'SEEDING DB'
      - name: Run Tests
        run: echo 'RUNNING TESTS'
      - name: Run E2E Tests
        run: echo 'RUNNING E2E TESTS'
