name: Test

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      TZ: ${{ vars.TZ }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_NAME: ${{ vars.DB_NAME }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
      REDIS_PORT: ${{ vars.REDIS_PORT }}
      REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
      CACHE_TTL: ${{ vars.CACHE_TTL }}
      RATE_LIMITER_TTL: ${{ vars.RATE_LIMITER_TTL }}
      RATE_LIMITER_LIMIT: ${{ vars.RATE_LIMITER_LIMIT }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Environment
        run: yarn env:test:up:detached
      - name: Run Migrations
        run: yarn db:migration:run
      - name: Seeding Database
        run: echo 'SEEDING DB'
      - name: Run Tests
        run: yarn test
      - name: Run E2E Tests
        run: yarn test:e2e
